### ISSUE TITLE
investigate TLS

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang-nursery/thanks#14]
People are gonna want this, even though it's just informational.

**Comment by lfairy** [comment]
I've found success with Cloudflare. I think it's perfect for this site actually. Since Contributors is just a few static pages, the CDN will likely cache them all, and keep serving its own copy when the original server goes down.

**Comment by steveklabnik** [comment]
Yeah, we'll see. I forgot that, since this doesn't have a custom domain, it already has SSL, thanks to heroku. If this were ever to be contributors.rust-lang.org, it'd get SSL through that. So I really don't think that there's anything to do here; I'll leave it open for a while just in case.

**Comment by steveklabnik** [comment]
Now that this has moved to http://thanks.rust-lang.org/ , things are a bit different. I've pinged @alexcrichton about why `https` still gives an error; it's using heroku's cert rather than rust-lang.org's. Might be a switch I need to flip, might be one he does.

**Comment by steveklabnik** [comment]
Okay so https://thanks.rust-lang.org _should_ work, and it did once for me, but isn't again. I think it's just DNS; let's wait for it to shake out, i guess?

**Comment by steveklabnik** [comment]
I asked in `#rust-beginners` and it seems that it's secure for most people, though one person is getting an issue. I'm going to leave this open but I think it's good.

**Comment by steveklabnik** [comment]
This is now done, and all HTTP traffic redirects to HTTPS. Closing!
