### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by artemgurzhii** [rust-lang-nursery/thanks#17]
Can this [part of code](https://github.com/steveklabnik/contributors/blob/e42a29d33cd8ada841371d0e14aab1e186fd5869/src/bin/populate.rs#L119-L149) be optimized using the for loop?

**Comment by steveklabnik** [comment]
Possibly; I wasn't sure. I'd be happy to take a patch fixing this!

**Comment by lfairy** [comment]
A more general solution may be to infer the releases from git tags.

Here's what `git tag -n` looks like right now:

```
0.1             0.1 release
0.10            0.10 release
0.11.0          0.11.0 release
0.12.0          0.12.0 release
0.2             0.2 release
0.3             0.3 release
0.4             0.4 release
0.5             0.5 release
0.6             0.6 release
0.7             0.7 release
0.8             0.8 release
0.9             0.9 release
1.0.0           1.0.0 release
1.0.0-alpha     1.0.0-alpha release
1.0.0-alpha.2   1.0.0-alpha.2 release
1.0.0-beta      1.0.0-beta
1.1.0           1.1.0 release
1.2.0           1.2.0 release
1.3.0           1.3.0 release
1.4.0           1.4.0 release
1.5.0           1.5.0 release
homu-tmp        Auto merge of #30566 - salty-horse:doc_typo, r=apasel422
release-0.1     0.1 release
release-0.2     0.2 release
release-0.3     0.3 release
release-0.3.1   release 0.3.1
release-0.4     0.4 release
release-0.5     0.5 release
release-0.6     0.6 release
release-0.7     0.7 release
```

So any tag whose name starts with a digit (`\d.*`) can be considered a "release". If we support other repositories (#8), then we can make this a configurable regex as well.

**Comment by steveklabnik** [comment]
> A more general solution may be to infer the releases from git tags.

Yeah, this would be okay. I didn't worry about it too much because we want to run the script to update every release on release day, so for production, this should be fine, but it'd be nice if anyone getting started would have an updated database right away.

The hard part isn't figuring it out from tags though; it's also calculating the previous release. I'm sure it's fairly easy with iterators, somehow.

**Comment by artemgurzhii** [comment]
```rust
let releases = ["0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "0.10", "0.11.0", "0.12.0", "1.0.0-alpha", "1.0.0-alpha.2", "1.0.0-beta", "1.0.0", "1.1.0", "1.2.0", "1.3.0", "1.4.0", "1.5.0", "1.6.0", "1.7.0", "1.8.0", "1.9.0", "1.10.0", "1.11.0", "1.12.0", "1.12.1", "1.13.0", "1.14.0", "master"];

for (i, release) in releases.iter().enumerate() {
    if releases[i] == "master" {
        break;
    } else if releases[i+1] == "1.13.0" {
        println!("assign_commits({:?}, {:?});", releases[i+1], releases[i-1]);
    } else {
        println!("assign_commits({:?}, {:?});", releases[i+1], release);
    }
}

**Comment by jmatraszek** [comment]
Infering releases for git tags is something we have to have for supporting multiple projects (or at least have the tags not hardcoded in the source).

**Comment by steveklabnik** [comment]
Inferring tags is now happening; there's some issues with it still, but I think this ticket can be closed. Thanks all!
