### ISSUE TITLE
Link to GitHub from the site

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang-nursery/thanks#18]
Yup. No way to find this from there.

**Comment by maccoda** [comment]
Any particular way you were wanting to do this? Just a link in first section of the README like so? Or something a bit nicer?
___
This [web application](https://rust-contributors.herokuapp.com/) shows the people who have contributed to Rust.

**Comment by steveklabnik** [comment]
> Just a link in first section of the README like so?

The other way around! The site should have a link to the github repo. I'm not sure how to do it; maybe an "about" page would be a good idea.

**Comment by maccoda** [comment]
Ah! I misunderstood. Although do you think the link this way is all that bad either as I had to go back to your post when I wanted to open the page again?
Regardless the about page is a nice idea, or perhaps a footer of the usual made with love on GitHub line... I will play around with some ideas 😀

**Comment by steveklabnik** [comment]
> Although do you think the link this way is all that bad either

Nope! There already is one though: 
<img width="449" alt="untitled" src="https://cloud.githubusercontent.com/assets/27786/22261406/c9fc3356-e23a-11e6-9124-dd88837e1079.png">

**Comment by maccoda** [comment]
Ah many apologies! I missed that one!! My bad

**Comment by steveklabnik** [comment]
This was fixed in https://github.com/rust-lang-nursery/thanks/commit/27ffde4f6ea6d9aa26ecee324cb1137b69d802ce
