### ISSUE TITLE
use bulk inserts to speed up populate

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang-nursery/thanks#34]
Right now, populate takes a very long time because it sends a query for every one of the 60,000+ commits. Doing this in bulk would be a Good Idea.

**Comment by DorianListens** [comment]
I started looking at this last night.
It isn't just that it makes a query for every single commit, it makes at least two.

Currently, thanks lists out the full git log, adds all the commits and marks them as being from release 0.1, and then goes through each release, and updates all the commits from that release.

I think the solution here is to do a single pass through all of the releases, and add all of their commits marked with the correct release id up front. We can do bulk inserts as well, we should only need one query per release.

I've got a prototype of this refactoring on my machine, and I'll put up a PR in the next few days once I've cleaned it up and tested it against the current implementation.

**Comment by steveklabnik** [comment]
Thanks so much! That makes sense.

**Comment by DorianListens** [comment]
Given the changes in #72, I'm going to have to re-think my approach. I'll wait until that gets merged before digging back into this.

**Comment by steveklabnik** [comment]
I _believe_ this was effectively fixed by https://github.com/rust-lang-nursery/thanks/pull/82. I'm gonna do a lot of re-working anyway, so I think I'm gonna close this. PRs to do less queries very welcome!

**Comment by DorianListens** [comment]
Totally makes sense.
