### ISSUE TITLE
Improved mailmap support

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang-nursery/thanks#35]
I don't know if GitHub's API will respect the local mailmap or not. If not, we'll have to do it ourselves.

**Comment by JanZerebecki** [comment]
It does not. E.g. compare https://api.github.com/repos/rust-lang/rust/commits?sha=3a610e98a292f5bc75a720aa15c3600787a5ddb2 with `git show --use-mailmap 3a610e98a292f5bc75a720aa15c3600787a5ddb2`.

**Comment by steveklabnik** [comment]
This has happened!
