### ISSUE TITLE
Investigate differences between github counts and our counts

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang-nursery/thanks#41]
As far as I know, GitHub doesn't post how they calculate their numbers, so this might be hard. But compare

https://github.com/rust-lang/rust/graphs/contributors

to 

https://thanks.rust-lang.org/all-time

for my results. 770 vs 1600. Other people's, like @brson's, are pretty close.

**Comment by Manishearth** [comment]
Github ignores merge commits. This is why I'm near the top 😄

**Comment by Manishearth** [comment]
Oh, also, github will coalesce emails belonging to the same user, which we may not.

**Comment by steveklabnik** [comment]
We do have a mailmap and it is supported, so for the second one that might be fine.

I was wondering about merge commits. My rollups probably inflate my numbers.

**Comment by steveklabnik** [comment]
Seems fine, gonna close this.
