### ISSUE TITLE
I'm so nice, I'm listed twice! <3

### ISSUE THREAD

**Issue by carols10cents** [rust-lang-nursery/thanks#45]
I changed my git and/or github display name at some point, so I'm listed under both "Carol Nichols" and "Carol (Nichols || Goulding)". I'd prefer the latter. I'm *pretty* sure my git emails match.

**Comment by steveklabnik** [comment]
We should investigate fixing this in rust's mailmap 👍 then it'll get pulled into here.

**Comment by steveklabnik** [comment]
rustlang PR was merged, so I'm going to give this a close. This will be fixed on its own before thursday. Thanks!
