### ISSUE TITLE
Listed twice

### ISSUE THREAD

**Issue by jethrogb** [rust-lang-nursery/thanks#51]
I'm listed as jethrogb and Jethro Beekman. I guess this could be because I intentionally haven't linked my git e-mail address with GitHub. If you answer is ”deal with it” I can accept that.

**Comment by steveklabnik** [comment]
It's easy to fix! What would you prefer to show up as?

**Comment by jethrogb** [comment]
Jethro Beekman

**Comment by steveklabnik** [comment]
PR sent to the main repo

**Comment by steveklabnik** [comment]
rustlang PR was merged, so I'm going to give this a close. This will be fixed on its own before thursday. Thanks!
