### ISSUE TITLE
Releases: sort 1.0.0-alpha "before" 1.0.0

### ISSUE THREAD

**Issue by elahn** [rust-lang-nursery/thanks#61]
On the main page in the list of releases, 1.0.0 should appear above [1.0.0-beta, 1.0.0-alpha.2, 1.0.0-alpha].

This could be solved by a custom sorting algorithm or by adding `release_date` to the `releases` table and sorting on that.

Question: will patch releases for a rust version ever be released after a new minor version release? If so, should these be sorted chronologically, or by relative version?

**Comment by steveklabnik** [comment]
> will patch releases for a rust version ever be released after a new minor version release?

We've done this once, for 1.12.1. It's not something that should happen very often.

>  If so, should these be sorted chronologically, or by relative version?

I'd argue that everything should be in semver order; which is how I think this could be fixed; take all the releases, put master on top, then in descending order. Luckily I know a crate for that 😉

**Comment by steveklabnik** [comment]
There's a lot more than just this one sort ordering wrong.
