### ISSUE TITLE
Listed twice

### ISSUE THREAD

**Issue by gifnksm** [rust-lang-nursery/thanks#71]
My name is listed twice:

  * gifnksm
  * NAKASHIMA, Makoto

I prefer the latter.

**Comment by steveklabnik** [comment]
Sorry about that @gifnksm ! Looks like there's three ways you're in the history:

* gifnksm: makoto.nksm+github@gmail.com
* gifnksm: makoto.nksm@gmail.com
* NAKASHIMA, Makoto: makoto.nksm+github@gmail.com

I am assuming that you prefer to leave the `+github` in there? I will look up how to merge these three to the mailmap.

**Comment by JanZerebecki** [comment]
The current .mailmap doesn't explain any changes showing up as authored with the name `gifnksm` (tested by checking the output of `git shortlog`), so something is currently not honouring the mailmap.

**Comment by steveklabnik** [comment]
I just checked in on this, and you are now only `NAKASHIMA, Makoto`. Sorry for taking so long to double check here.
